FROM rayproject/ray:latest-gpu

RUN whoami

# (Optional) if your image doesn't already have it
# COPY requirements_compiled.txt /home/ray/requirements_compiled.txt

USER root

# Setup workspace
RUN mkdir -p /workspace/code && chmod -R a+rwX /workspace
WORKDIR /workspace/code

# First copy the constraints file
# COPY requirements_compiled.txt /home/ray/requirements_compiled.txt

# Install dependencies
RUN pip install --upgrade pip setuptools wheel && \
    #
    # Install TensorFlow with GPU support (from PyPI + optional NGC fallback)
    #
    # pip install tensorflow[and-cuda] && \
    #
    # Install PyTorch from the custom index
    #
    pip install --no-cache-dir \
        torch \
        torchvision \
        torchaudio \
        --extra-index-url https://download.pytorch.org/whl/cu126  && \
    #
    # Install remaining packages from default PyPI
    #
    pip install --no-cache-dir \
        gymnasium \
        jupyterlab \
        notebook \
        gputil \
        -c /home/ray/requirements_compiled.txt

EXPOSE 8888

CMD ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--allow-root", "--no-browser"]
