# Step 1: Use a base image with CUDA 12.3 support
# FROM nvidia/cuda:12.3.2-cudnn9-runtime-ubuntu22.04
FROM nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu22.04

# USER root

# Step 8: Create a workspace directory
RUN mkdir -p /workspace/code && chmod -R 777 /workspace
WORKDIR /workspace/code

# Step 2: Set environment variables
ENV DEBIAN_FRONTEND=noninteractive \
    LANG=C.UTF-8 \
    LC_ALL=C.UTF-8 \
    PYTHONUNBUFFERED=1

# Step 3: Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    curl \
    git \
    libgl1-mesa-glx \
    libglib2.0-0 \
    wget \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

# Step 4: Upgrade pip and install Jupyter Notebook
RUN pip install --upgrade pip setuptools wheel \
    && pip install jupyterlab notebook

# Step 5: Install TensorFlow 2.19 with GPU support
RUN pip install tensorflow=2.12

# Install gymnasium (gym deprecated)
RUN pip install --no-cache-dir gymnasium

# Step 7: Install Ray[rllib] 2.47.1
RUN pip install ray[rllib]==2.47.1

# Step 9: Expose the Jupyter Notebook port
EXPOSE 8888

# Step 10: Define the default command to start Jupyter Notebook
CMD ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--allow-root", "--no-browser"]
